### ISSUE TITLE
Function readEvidenceFile doesn't work

### ISSUE THREAD

**Issue by sago91** [bartongroup/Proteus#35]
> library(proteusLabelFree)
> evidenceFile <- system.file("extdata", "evidence.txt.gz", package="proteusLabelFree")
> evi <- readEvidenceFile(evidenceFile)
Error in readEvidenceFile(evidenceFile) : 
  impossible de trouver la fonction "readEvidenceFile"

is someone could help me

**Comment by RubenRBakker** [comment]
I am not involved in the development of proteus but also a user. I think you should try: 

library(proteus)
evi <- readEvidenceFile("evidencefilename.txt")
metadata <- same thing as above. 

I think it is two fold, firstly is that proteus is the package and proteusLabelFree is the vignette. Use library on the package. Secondly, that system.file(..., package = "proteusLabelFree") might not work for you because it wasn't installed properly. Instead of spending a lot of time to make that work, I'd suggest downloading the evidence.txt file and metadata.txt directly from the github. Put it in the folder with your script and just read it in like any other file. 

Good luck!

**Comment by sago91** [comment]
Hi, 
thanks for your answer,
yes it seems to be an installation issue
  creating vignettes (21.9s)
   --- re-building ‘SILAC.Rmd’ using rmarkdown
   Quitting from lines 30-32 (SILAC.Rmd) 
   Error: processing vignette 'SILAC.Rmd' failed with diagnostics:
   there is no package called 'proteusSILAC'
   --- failed re-building ‘SILAC.Rmd’
   
   --- re-building ‘TMT.Rmd’ using rmarkdown
   Quitting from lines 30-32 (TMT.Rmd) 
   Error: processing vignette 'TMT.Rmd' failed with diagnostics:
   there is no package called 'proteusTMT'
   --- failed re-building ‘TMT.Rmd’
   
   --- re-building ‘proteus.Rmd’ using rmarkdown
   Warning: Removed 2 rows containing non-finite values (stat_binhex).
   Warning: Removed 9 row(s) containing missing values (geom_path).
   Warning: Partial NA coefficients for 4 probe(s)
   Warning: Removed 82 rows containing non-finite values (stat_boxplot).
   Warning: Removed 82 rows containing missing values (geom_point).
   Warning: Removed 82 rows containing non-finite values (stat_boxplot).
   Warning: Removed 82 rows containing missing values (geom_point).
   --- finished re-building ‘proteus.Rmd’
   
   SUMMARY: processing the following files failed:
     ‘SILAC.Rmd’ ‘TMT.Rmd’
   
   Erreur : Vignette re-building failed.
   Exécution arrêtée
